import type { Chef, Recipe, RecipeComponent, Ingredient, Collection, CollectionRecipe } from './types';

// ===== 5 Chefs =====
export const SEED_CHEFS: Chef[] = [
  {
    id: 'chef-1',
    email: 'rene@noma.dk',
    display_name: 'René Redzepi',
    avatar_url: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=200&h=200&fit=crop',
    restaurant: 'Noma',
    country: 'Denmark',
    bio: 'Pioneer of New Nordic cuisine. Three-time winner of The World\'s 50 Best Restaurants.',
    is_verified: true,
    membership_plan: 'elite',
    follower_count: 24500,
  },
  {
    id: 'chef-2',
    email: 'massimo@osteria.it',
    display_name: 'Massimo Bottura',
    avatar_url: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?w=200&h=200&fit=crop',
    restaurant: 'Osteria Francescana',
    country: 'Italy',
    bio: 'Chef-patron of Osteria Francescana. Blending tradition with avant-garde creativity.',
    is_verified: true,
    membership_plan: 'elite',
    follower_count: 31200,
  },
  {
    id: 'chef-3',
    email: 'dominique@atelier.fr',
    display_name: 'Dominique Crenn',
    avatar_url: 'https://images.unsplash.com/photo-1595257841889-eca2678571fa?w=200&h=200&fit=crop',
    restaurant: 'Atelier Crenn',
    country: 'France',
    bio: 'First female chef in the US to receive three Michelin stars. Poetic culinaria.',
    is_verified: true,
    membership_plan: 'elite',
    follower_count: 18700,
  },
  {
    id: 'chef-4',
    email: 'yoshihiro@narisawa.jp',
    display_name: 'Yoshihiro Narisawa',
    avatar_url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=200&h=200&fit=crop',
    restaurant: 'Narisawa',
    country: 'Japan',
    bio: 'Known for "Innovative Satoyama Cuisine" bridging nature and gastronomy.',
    is_verified: true,
    membership_plan: 'pro',
    follower_count: 15300,
  },
  {
    id: 'chef-5',
    email: 'ana@mugaritz.es',
    display_name: 'Andoni Luis Aduriz',
    avatar_url: 'https://images.unsplash.com/photo-1583394293214-28ez924e867c?w=200&h=200&fit=crop',
    restaurant: 'Mugaritz',
    country: 'Spain',
    bio: 'Culinary philosopher pushing the boundaries of taste and texture at Mugaritz.',
    is_verified: true,
    membership_plan: 'pro',
    follower_count: 12800,
  },
];

// ===== 12 Recipes =====
export const SEED_RECIPES: Recipe[] = [
  {
    id: 'recipe-1',
    chef_id: 'chef-1',
    title: 'Forager\'s Wild Herb Salad',
    description: 'A celebration of Nordic terroir featuring 20+ hand-foraged herbs and flowers from the Danish countryside, dressed with a fermented plum vinaigrette.',
    hero_image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=500&fit=crop',
    cuisine_type: 'nordic',
    season_tags: ['spring', 'summer'],
    tier: 'legendary',
    access_level: 'free',
    prep_time_minutes: 45,
    total_time_minutes: 60,
    servings: 4,
    likes_count: 1842,
    comments_count: 234,
    is_published: true,
  },
  {
    id: 'recipe-2',
    chef_id: 'chef-1',
    title: 'Sea Urchin & Buttermilk',
    description: 'Delicate sea urchin served on a bed of buttermilk snow with dill oil and crispy rye.',
    hero_image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=500&fit=crop',
    cuisine_type: 'nordic',
    season_tags: ['winter'],
    tier: 'top',
    access_level: 'pro',
    prep_time_minutes: 30,
    total_time_minutes: 45,
    servings: 2,
    likes_count: 956,
    comments_count: 87,
    is_published: true,
  },
  {
    id: 'recipe-3',
    chef_id: 'chef-2',
    title: 'Five Ages of Parmigiano Reggiano',
    description: 'A legendary dish presenting Parmigiano Reggiano in five different textures and temperatures, from a 24-month foam to a 50-month crisp.',
    hero_image_url: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=500&fit=crop',
    cuisine_type: 'italian',
    season_tags: ['all_season'],
    tier: 'legendary',
    access_level: 'elite',
    prep_time_minutes: 120,
    total_time_minutes: 180,
    servings: 4,
    likes_count: 2341,
    comments_count: 312,
    is_published: true,
  },
  {
    id: 'recipe-4',
    chef_id: 'chef-2',
    title: 'Oops! I Dropped the Lemon Tart',
    description: 'The iconic deconstructed lemon tart that turned a kitchen accident into culinary art.',
    hero_image_url: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800&h=500&fit=crop',
    cuisine_type: 'italian',
    season_tags: ['all_season'],
    tier: 'bocuse_collection',
    access_level: 'pro',
    prep_time_minutes: 90,
    total_time_minutes: 150,
    servings: 6,
    likes_count: 3105,
    comments_count: 445,
    is_published: true,
  },
  {
    id: 'recipe-5',
    chef_id: 'chef-3',
    title: 'Walking on the Ocean Floor',
    description: 'A poetic seafood composition inspired by the depths of the Pacific, featuring abalone, sea vegetables, and coastal herbs.',
    hero_image_url: 'https://images.unsplash.com/photo-1535140728325-a4d3707eee61?w=800&h=500&fit=crop',
    cuisine_type: 'french',
    season_tags: ['summer', 'autumn'],
    tier: 'legendary',
    access_level: 'elite',
    prep_time_minutes: 60,
    total_time_minutes: 90,
    servings: 2,
    likes_count: 1567,
    comments_count: 198,
    is_published: true,
  },
  {
    id: 'recipe-6',
    chef_id: 'chef-3',
    title: 'Brioche Feuilletée',
    description: 'A fusion of brioche and croissant techniques creating an impossibly flaky, buttery bread.',
    hero_image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=500&fit=crop',
    cuisine_type: 'french',
    season_tags: ['all_season'],
    tier: 'featured',
    access_level: 'free',
    prep_time_minutes: 180,
    total_time_minutes: 360,
    servings: 8,
    likes_count: 2890,
    comments_count: 567,
    is_published: true,
  },
  {
    id: 'recipe-7',
    chef_id: 'chef-4',
    title: 'Soil of the Forest',
    description: 'Narisawa\'s signature dish representing the Japanese forest floor using burdock root cooked in actual soil.',
    hero_image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=500&fit=crop',
    cuisine_type: 'japanese',
    season_tags: ['autumn'],
    tier: 'legendary',
    access_level: 'elite',
    prep_time_minutes: 90,
    total_time_minutes: 240,
    servings: 4,
    likes_count: 1923,
    comments_count: 267,
    is_published: true,
  },
  {
    id: 'recipe-8',
    chef_id: 'chef-4',
    title: 'Sakura Masu with Cherry Blossom',
    description: 'Spring cherry trout paired with preserved cherry blossoms, yuzu, and mountain herbs.',
    hero_image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=500&fit=crop',
    cuisine_type: 'japanese',
    season_tags: ['spring'],
    tier: 'top',
    access_level: 'pro',
    prep_time_minutes: 45,
    total_time_minutes: 75,
    servings: 2,
    likes_count: 1102,
    comments_count: 145,
    is_published: true,
  },
  {
    id: 'recipe-9',
    chef_id: 'chef-5',
    title: 'Edible Stones',
    description: 'Mugaritz\'s famous edible stones - potatoes disguised as river pebbles with a kaolin clay coating.',
    hero_image_url: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&h=500&fit=crop',
    cuisine_type: 'spanish',
    season_tags: ['all_season'],
    tier: 'bocuse_collection',
    access_level: 'pro',
    prep_time_minutes: 120,
    total_time_minutes: 180,
    servings: 4,
    likes_count: 2456,
    comments_count: 334,
    is_published: true,
  },
  {
    id: 'recipe-10',
    chef_id: 'chef-5',
    title: 'Burnt Onion Ash Broth',
    description: 'A deeply umami broth made from charred onions, served with a delicate mushroom custard.',
    hero_image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=500&fit=crop',
    cuisine_type: 'spanish',
    season_tags: ['winter', 'autumn'],
    tier: 'featured',
    access_level: 'free',
    prep_time_minutes: 60,
    total_time_minutes: 120,
    servings: 4,
    likes_count: 876,
    comments_count: 102,
    is_published: true,
  },
  {
    id: 'recipe-11',
    chef_id: 'chef-2',
    title: 'Tortellini in Brodo',
    description: 'Traditional Modenese tortellini in a crystal-clear capon broth, perfected over decades.',
    hero_image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&h=500&fit=crop',
    cuisine_type: 'italian',
    season_tags: ['winter'],
    tier: 'base',
    access_level: 'free',
    prep_time_minutes: 120,
    total_time_minutes: 240,
    servings: 6,
    likes_count: 1345,
    comments_count: 189,
    is_published: true,
  },
  {
    id: 'recipe-12',
    chef_id: 'chef-1',
    title: 'Fermented Mushroom Garum',
    description: 'A versatile fermented mushroom sauce inspired by ancient Roman garum, developed over months of fermentation.',
    hero_image_url: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=800&h=500&fit=crop',
    cuisine_type: 'nordic',
    season_tags: ['all_season'],
    tier: 'featured',
    access_level: 'free',
    prep_time_minutes: 30,
    total_time_minutes: 43200,
    servings: 20,
    likes_count: 2100,
    comments_count: 356,
    is_published: true,
  },
];

// ===== Recipe Components =====
export const SEED_COMPONENTS: RecipeComponent[] = [
  // Recipe 1: Forager's Wild Herb Salad
  { id: 'comp-1-1', recipe_id: 'recipe-1', name: 'Wild Herb Salad', image_url: '', instructions: 'Gently wash and dry all foraged herbs. Arrange on chilled plates, mixing textures and colors. Reserve delicate flowers for garnish.', sort_order: 1 },
  { id: 'comp-1-2', recipe_id: 'recipe-1', name: 'Fermented Plum Vinaigrette', image_url: '', instructions: 'Blend fermented plums until smooth. Whisk in rapeseed oil slowly to emulsify. Season with sea salt and a touch of honey. Strain through fine mesh.', sort_order: 2 },
  // Recipe 2: Sea Urchin & Buttermilk
  { id: 'comp-2-1', recipe_id: 'recipe-2', name: 'Buttermilk Snow', image_url: '', instructions: 'Combine buttermilk with gellan gum. Set in a shallow tray and freeze. Scrape with a fork to create snow texture.', sort_order: 1 },
  { id: 'comp-2-2', recipe_id: 'recipe-2', name: 'Sea Urchin & Assembly', image_url: '', instructions: 'Clean sea urchin carefully. Place buttermilk snow in chilled bowls. Nestle sea urchin on top. Drizzle with dill oil and scatter crispy rye.', sort_order: 2 },
  // Recipe 3: Five Ages of Parmigiano
  { id: 'comp-3-1', recipe_id: 'recipe-3', name: 'Parmigiano Foam (24-month)', image_url: '', instructions: 'Infuse cream with 24-month Parmigiano rinds. Strain, season, and charge in a siphon with 2 N2O cartridges.', sort_order: 1 },
  { id: 'comp-3-2', recipe_id: 'recipe-3', name: 'Parmigiano Soufflé (36-month)', image_url: '', instructions: 'Prepare a classic soufflé base using béchamel and finely grated 36-month Parmigiano. Fold in whipped egg whites. Bake at 190°C for 12 minutes.', sort_order: 2 },
  { id: 'comp-3-3', recipe_id: 'recipe-3', name: 'Parmigiano Crisp (50-month)', image_url: '', instructions: 'Grate 50-month Parmigiano finely. Spread in thin circles on silicone mat. Bake at 180°C until golden and crispy.', sort_order: 3 },
  // Recipe 4: Oops! Lemon Tart
  { id: 'comp-4-1', recipe_id: 'recipe-4', name: 'Lemon Curd', image_url: '', instructions: 'Whisk eggs, sugar, and lemon juice over bain-marie until thick. Remove from heat and whisk in cold butter pieces until glossy.', sort_order: 1 },
  { id: 'comp-4-2', recipe_id: 'recipe-4', name: 'Shortcrust Crumble', image_url: '', instructions: 'Make a classic pâte sucrée. Instead of lining a tart tin, crumble randomly onto a baking sheet. Bake until golden.', sort_order: 2 },
  { id: 'comp-4-3', recipe_id: 'recipe-4', name: 'Meringue Shards', image_url: '', instructions: 'Whip egg whites and sugar to stiff peaks. Spread thin on parchment and dry in oven at 90°C for 2 hours. Break into shards.', sort_order: 3 },
  // Recipe 5: Walking on Ocean Floor
  { id: 'comp-5-1', recipe_id: 'recipe-5', name: 'Abalone Preparation', image_url: '', instructions: 'Tenderize abalone and slow-cook sous vide at 62°C for 4 hours. Slice thinly and sear briefly before serving.', sort_order: 1 },
  { id: 'comp-5-2', recipe_id: 'recipe-5', name: 'Ocean Broth', image_url: '', instructions: 'Simmer kelp, bonito, and coastal herbs for a clear, intensely oceanic broth. Strain and season with yuzu.', sort_order: 2 },
  // Recipe 6: Brioche Feuilletée
  { id: 'comp-6-1', recipe_id: 'recipe-6', name: 'Brioche Dough', image_url: '', instructions: 'Combine flour, eggs, sugar, yeast, and salt. Knead until smooth. Incorporate softened butter gradually. Rest overnight in refrigerator.', sort_order: 1 },
  { id: 'comp-6-2', recipe_id: 'recipe-6', name: 'Lamination', image_url: '', instructions: 'Roll out dough and enclose a butter block. Perform 3 single folds with 30-minute rests between each. Shape and proof for 2 hours. Bake at 175°C.', sort_order: 2 },
  // Recipe 7: Soil of the Forest
  { id: 'comp-7-1', recipe_id: 'recipe-7', name: 'Burdock in Soil', image_url: '', instructions: 'Wrap burdock root in sanitized charcoal-rich soil. Slow-roast at 160°C for 3 hours. The soil imparts an earthy mineral quality.', sort_order: 1 },
  { id: 'comp-7-2', recipe_id: 'recipe-7', name: 'Forest Floor Assembly', image_url: '', instructions: 'Create an edible soil from dehydrated mushrooms, rye bread, and miso. Plate the burdock and cover with edible soil. Garnish with micro herbs.', sort_order: 2 },
  // Recipe 8: Sakura Masu
  { id: 'comp-8-1', recipe_id: 'recipe-8', name: 'Cured Sakura Masu', image_url: '', instructions: 'Cure the trout with salt, sugar, and preserved cherry blossom leaves for 24 hours. Rinse and slice thinly.', sort_order: 1 },
  { id: 'comp-8-2', recipe_id: 'recipe-8', name: 'Cherry Blossom Gel & Garnish', image_url: '', instructions: 'Make a gel from cherry blossom tea with agar. Set, dice, and arrange with yuzu zest and mountain herbs over the cured fish.', sort_order: 2 },
  // Recipe 9: Edible Stones
  { id: 'comp-9-1', recipe_id: 'recipe-9', name: 'Potato Stones', image_url: '', instructions: 'Boil small potatoes until just tender. Cool completely. Coat with a mixture of kaolin clay and olive oil to create a stone-like exterior.', sort_order: 1 },
  { id: 'comp-9-2', recipe_id: 'recipe-9', name: 'Dipping Sauce', image_url: '', instructions: 'Blend roasted peppers, smoked paprika, garlic, and olive oil. Season with sherry vinegar and serve alongside the stones.', sort_order: 2 },
  // Recipe 10: Burnt Onion Ash Broth
  { id: 'comp-10-1', recipe_id: 'recipe-10', name: 'Charred Onion Broth', image_url: '', instructions: 'Halve onions and char cut-side down until completely black. Simmer in water for 3 hours. Strain through cheesecloth for a clear, smoky broth.', sort_order: 1 },
  { id: 'comp-10-2', recipe_id: 'recipe-10', name: 'Mushroom Custard', image_url: '', instructions: 'Infuse cream with dried porcini for 1 hour. Strain, combine with eggs. Pour into molds and steam at 85°C for 20 minutes.', sort_order: 2 },
  // Recipe 11: Tortellini in Brodo
  { id: 'comp-11-1', recipe_id: 'recipe-11', name: 'Fresh Pasta Dough', image_url: '', instructions: 'Combine 00 flour and eggs. Knead for 10 minutes until silky smooth. Rest wrapped for 30 minutes.', sort_order: 1 },
  { id: 'comp-11-2', recipe_id: 'recipe-11', name: 'Filling & Assembly', image_url: '', instructions: 'Mix ground pork, prosciutto, mortadella, and Parmigiano. Roll pasta thin, cut squares, fill and fold into tortellini shape.', sort_order: 2 },
  { id: 'comp-11-3', recipe_id: 'recipe-11', name: 'Capon Broth', image_url: '', instructions: 'Simmer capon with celery, carrot, and onion for 4 hours. Skim regularly. Strain and season. Cook tortellini directly in the broth.', sort_order: 3 },
  // Recipe 12: Fermented Mushroom Garum
  { id: 'comp-12-1', recipe_id: 'recipe-12', name: 'Mushroom Preparation', image_url: '', instructions: 'Combine mixed wild mushrooms with barley koji and 15% salt by weight. Pack tightly into fermentation vessel.', sort_order: 1 },
  { id: 'comp-12-2', recipe_id: 'recipe-12', name: 'Fermentation & Pressing', image_url: '', instructions: 'Ferment at 28°C for 90 days, stirring weekly. Strain through cheesecloth, pressing to extract all liquid. Pasteurize at 80°C and bottle.', sort_order: 2 },
];

// ===== Ingredients =====
export const SEED_INGREDIENTS: Ingredient[] = [
  // comp-1-1: Wild Herb Salad
  { id: 'ing-1', component_id: 'comp-1-1', name: 'Mixed wild herbs', quantity: 200, unit: 'g', sort_order: 1 },
  { id: 'ing-2', component_id: 'comp-1-1', name: 'Edible flowers', quantity: 30, unit: 'g', sort_order: 2 },
  { id: 'ing-3', component_id: 'comp-1-1', name: 'Wood sorrel', quantity: 50, unit: 'g', sort_order: 3 },
  // comp-1-2: Vinaigrette
  { id: 'ing-4', component_id: 'comp-1-2', name: 'Fermented plums', quantity: 100, unit: 'g', sort_order: 1 },
  { id: 'ing-5', component_id: 'comp-1-2', name: 'Rapeseed oil', quantity: 60, unit: 'ml', sort_order: 2 },
  { id: 'ing-6', component_id: 'comp-1-2', name: 'Honey', quantity: 10, unit: 'g', sort_order: 3 },
  { id: 'ing-7', component_id: 'comp-1-2', name: 'Sea salt', quantity: 2, unit: 'g', sort_order: 4 },
  // comp-2-1: Buttermilk Snow
  { id: 'ing-8', component_id: 'comp-2-1', name: 'Buttermilk', quantity: 300, unit: 'ml', sort_order: 1 },
  { id: 'ing-9', component_id: 'comp-2-1', name: 'Gellan gum', quantity: 3, unit: 'g', sort_order: 2 },
  // comp-2-2: Sea Urchin
  { id: 'ing-10', component_id: 'comp-2-2', name: 'Fresh sea urchin', quantity: 4, unit: 'pcs', sort_order: 1 },
  { id: 'ing-11', component_id: 'comp-2-2', name: 'Dill oil', quantity: 15, unit: 'ml', sort_order: 2 },
  { id: 'ing-12', component_id: 'comp-2-2', name: 'Crispy rye bread', quantity: 20, unit: 'g', sort_order: 3 },
  // comp-3-1: Parmigiano Foam
  { id: 'ing-13', component_id: 'comp-3-1', name: 'Heavy cream', quantity: 250, unit: 'ml', sort_order: 1 },
  { id: 'ing-14', component_id: 'comp-3-1', name: 'Parmigiano Reggiano 24-month', quantity: 80, unit: 'g', sort_order: 2 },
  // comp-3-2: Soufflé
  { id: 'ing-15', component_id: 'comp-3-2', name: 'Parmigiano Reggiano 36-month', quantity: 100, unit: 'g', sort_order: 1 },
  { id: 'ing-16', component_id: 'comp-3-2', name: 'Egg whites', quantity: 4, unit: 'pcs', sort_order: 2 },
  { id: 'ing-17', component_id: 'comp-3-2', name: 'Butter', quantity: 30, unit: 'g', sort_order: 3 },
  { id: 'ing-18', component_id: 'comp-3-2', name: 'Flour', quantity: 30, unit: 'g', sort_order: 4 },
  { id: 'ing-19', component_id: 'comp-3-2', name: 'Milk', quantity: 200, unit: 'ml', sort_order: 5 },
  // comp-3-3: Crisp
  { id: 'ing-20', component_id: 'comp-3-3', name: 'Parmigiano Reggiano 50-month', quantity: 60, unit: 'g', sort_order: 1 },
  // comp-4-1: Lemon Curd
  { id: 'ing-21', component_id: 'comp-4-1', name: 'Lemons (juice & zest)', quantity: 4, unit: 'pcs', sort_order: 1 },
  { id: 'ing-22', component_id: 'comp-4-1', name: 'Eggs', quantity: 3, unit: 'pcs', sort_order: 2 },
  { id: 'ing-23', component_id: 'comp-4-1', name: 'Sugar', quantity: 150, unit: 'g', sort_order: 3 },
  { id: 'ing-24', component_id: 'comp-4-1', name: 'Cold butter', quantity: 100, unit: 'g', sort_order: 4 },
  // comp-4-2: Shortcrust
  { id: 'ing-25', component_id: 'comp-4-2', name: 'Flour', quantity: 200, unit: 'g', sort_order: 1 },
  { id: 'ing-26', component_id: 'comp-4-2', name: 'Butter', quantity: 100, unit: 'g', sort_order: 2 },
  { id: 'ing-27', component_id: 'comp-4-2', name: 'Sugar', quantity: 60, unit: 'g', sort_order: 3 },
  { id: 'ing-28', component_id: 'comp-4-2', name: 'Egg yolk', quantity: 1, unit: 'pc', sort_order: 4 },
  // comp-4-3: Meringue
  { id: 'ing-29', component_id: 'comp-4-3', name: 'Egg whites', quantity: 2, unit: 'pcs', sort_order: 1 },
  { id: 'ing-30', component_id: 'comp-4-3', name: 'Sugar', quantity: 100, unit: 'g', sort_order: 2 },
  // comp-5-1: Abalone
  { id: 'ing-31', component_id: 'comp-5-1', name: 'Fresh abalone', quantity: 2, unit: 'pcs', sort_order: 1 },
  { id: 'ing-32', component_id: 'comp-5-1', name: 'Sea salt', quantity: 5, unit: 'g', sort_order: 2 },
  // comp-5-2: Ocean Broth
  { id: 'ing-33', component_id: 'comp-5-2', name: 'Kombu kelp', quantity: 20, unit: 'g', sort_order: 1 },
  { id: 'ing-34', component_id: 'comp-5-2', name: 'Bonito flakes', quantity: 30, unit: 'g', sort_order: 2 },
  { id: 'ing-35', component_id: 'comp-5-2', name: 'Coastal herbs', quantity: 15, unit: 'g', sort_order: 3 },
  { id: 'ing-36', component_id: 'comp-5-2', name: 'Yuzu juice', quantity: 10, unit: 'ml', sort_order: 4 },
  // comp-6-1: Brioche Dough
  { id: 'ing-37', component_id: 'comp-6-1', name: 'Bread flour', quantity: 500, unit: 'g', sort_order: 1 },
  { id: 'ing-38', component_id: 'comp-6-1', name: 'Eggs', quantity: 5, unit: 'pcs', sort_order: 2 },
  { id: 'ing-39', component_id: 'comp-6-1', name: 'Sugar', quantity: 60, unit: 'g', sort_order: 3 },
  { id: 'ing-40', component_id: 'comp-6-1', name: 'Fresh yeast', quantity: 15, unit: 'g', sort_order: 4 },
  { id: 'ing-41', component_id: 'comp-6-1', name: 'Salt', quantity: 10, unit: 'g', sort_order: 5 },
  { id: 'ing-42', component_id: 'comp-6-1', name: 'Softened butter', quantity: 200, unit: 'g', sort_order: 6 },
  // comp-6-2: Lamination
  { id: 'ing-43', component_id: 'comp-6-2', name: 'Cold butter block', quantity: 250, unit: 'g', sort_order: 1 },
  // comp-7-1: Burdock
  { id: 'ing-44', component_id: 'comp-7-1', name: 'Burdock root', quantity: 4, unit: 'pcs', sort_order: 1 },
  { id: 'ing-45', component_id: 'comp-7-1', name: 'Charcoal-rich soil (food-safe)', quantity: 500, unit: 'g', sort_order: 2 },
  // comp-7-2: Forest Floor
  { id: 'ing-46', component_id: 'comp-7-2', name: 'Dried shiitake mushrooms', quantity: 30, unit: 'g', sort_order: 1 },
  { id: 'ing-47', component_id: 'comp-7-2', name: 'Rye bread', quantity: 50, unit: 'g', sort_order: 2 },
  { id: 'ing-48', component_id: 'comp-7-2', name: 'White miso', quantity: 20, unit: 'g', sort_order: 3 },
  // comp-8-1: Cured Sakura Masu
  { id: 'ing-49', component_id: 'comp-8-1', name: 'Sakura masu (cherry trout)', quantity: 300, unit: 'g', sort_order: 1 },
  { id: 'ing-50', component_id: 'comp-8-1', name: 'Sea salt', quantity: 30, unit: 'g', sort_order: 2 },
  { id: 'ing-51', component_id: 'comp-8-1', name: 'Sugar', quantity: 15, unit: 'g', sort_order: 3 },
  { id: 'ing-52', component_id: 'comp-8-1', name: 'Preserved cherry blossom leaves', quantity: 10, unit: 'pcs', sort_order: 4 },
  // comp-8-2: Gel
  { id: 'ing-53', component_id: 'comp-8-2', name: 'Cherry blossom tea', quantity: 200, unit: 'ml', sort_order: 1 },
  { id: 'ing-54', component_id: 'comp-8-2', name: 'Agar agar', quantity: 2, unit: 'g', sort_order: 2 },
  { id: 'ing-55', component_id: 'comp-8-2', name: 'Yuzu zest', quantity: 5, unit: 'g', sort_order: 3 },
  // comp-9-1: Potato Stones
  { id: 'ing-56', component_id: 'comp-9-1', name: 'Small potatoes', quantity: 12, unit: 'pcs', sort_order: 1 },
  { id: 'ing-57', component_id: 'comp-9-1', name: 'Kaolin clay (food-grade)', quantity: 50, unit: 'g', sort_order: 2 },
  { id: 'ing-58', component_id: 'comp-9-1', name: 'Olive oil', quantity: 30, unit: 'ml', sort_order: 3 },
  // comp-9-2: Dipping Sauce
  { id: 'ing-59', component_id: 'comp-9-2', name: 'Roasted red peppers', quantity: 200, unit: 'g', sort_order: 1 },
  { id: 'ing-60', component_id: 'comp-9-2', name: 'Smoked paprika', quantity: 5, unit: 'g', sort_order: 2 },
  { id: 'ing-61', component_id: 'comp-9-2', name: 'Garlic', quantity: 2, unit: 'cloves', sort_order: 3 },
  { id: 'ing-62', component_id: 'comp-9-2', name: 'Sherry vinegar', quantity: 15, unit: 'ml', sort_order: 4 },
  // comp-10-1: Charred Onion Broth
  { id: 'ing-63', component_id: 'comp-10-1', name: 'Large onions', quantity: 6, unit: 'pcs', sort_order: 1 },
  { id: 'ing-64', component_id: 'comp-10-1', name: 'Water', quantity: 2, unit: 'L', sort_order: 2 },
  // comp-10-2: Mushroom Custard
  { id: 'ing-65', component_id: 'comp-10-2', name: 'Heavy cream', quantity: 200, unit: 'ml', sort_order: 1 },
  { id: 'ing-66', component_id: 'comp-10-2', name: 'Dried porcini', quantity: 30, unit: 'g', sort_order: 2 },
  { id: 'ing-67', component_id: 'comp-10-2', name: 'Eggs', quantity: 2, unit: 'pcs', sort_order: 3 },
  // comp-11-1: Fresh Pasta
  { id: 'ing-68', component_id: 'comp-11-1', name: '00 flour', quantity: 400, unit: 'g', sort_order: 1 },
  { id: 'ing-69', component_id: 'comp-11-1', name: 'Eggs', quantity: 4, unit: 'pcs', sort_order: 2 },
  // comp-11-2: Filling
  { id: 'ing-70', component_id: 'comp-11-2', name: 'Ground pork', quantity: 150, unit: 'g', sort_order: 1 },
  { id: 'ing-71', component_id: 'comp-11-2', name: 'Prosciutto di Parma', quantity: 80, unit: 'g', sort_order: 2 },
  { id: 'ing-72', component_id: 'comp-11-2', name: 'Mortadella', quantity: 80, unit: 'g', sort_order: 3 },
  { id: 'ing-73', component_id: 'comp-11-2', name: 'Parmigiano Reggiano', quantity: 60, unit: 'g', sort_order: 4 },
  // comp-11-3: Broth
  { id: 'ing-74', component_id: 'comp-11-3', name: 'Capon', quantity: 1, unit: 'whole', sort_order: 1 },
  { id: 'ing-75', component_id: 'comp-11-3', name: 'Celery', quantity: 2, unit: 'stalks', sort_order: 2 },
  { id: 'ing-76', component_id: 'comp-11-3', name: 'Carrot', quantity: 1, unit: 'pc', sort_order: 3 },
  { id: 'ing-77', component_id: 'comp-11-3', name: 'Onion', quantity: 1, unit: 'pc', sort_order: 4 },
  // comp-12-1: Mushroom Prep
  { id: 'ing-78', component_id: 'comp-12-1', name: 'Mixed wild mushrooms', quantity: 1000, unit: 'g', sort_order: 1 },
  { id: 'ing-79', component_id: 'comp-12-1', name: 'Barley koji', quantity: 200, unit: 'g', sort_order: 2 },
  { id: 'ing-80', component_id: 'comp-12-1', name: 'Sea salt', quantity: 180, unit: 'g', sort_order: 3 },
  // comp-12-2: Fermentation
  { id: 'ing-81', component_id: 'comp-12-2', name: 'Cheesecloth', quantity: 1, unit: 'sheet', sort_order: 1 },
];

// ===== 3 Collections =====
export const SEED_COLLECTIONS: Collection[] = [
  {
    id: 'coll-1',
    title: "Bocuse d'Or Masterworks",
    description: 'A curated collection of legendary dishes from past Bocuse d\'Or competitors and winners.',
    cover_image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=400&fit=crop',
    is_bocuse_official: true,
    sort_order: 1,
  },
  {
    id: 'coll-2',
    title: 'Nordic New Wave',
    description: 'The best of Scandinavian innovation — foraging, fermentation, and fire.',
    cover_image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop',
    is_bocuse_official: false,
    sort_order: 2,
  },
  {
    id: 'coll-3',
    title: 'Dessert Revolution',
    description: 'Boundary-pushing desserts that redefine the sweet course.',
    cover_image_url: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800&h=400&fit=crop',
    is_bocuse_official: false,
    sort_order: 3,
  },
];

export const SEED_COLLECTION_RECIPES: CollectionRecipe[] = [
  // Bocuse d'Or Masterworks
  { id: 'cr-1', collection_id: 'coll-1', recipe_id: 'recipe-1', sort_order: 1 },
  { id: 'cr-2', collection_id: 'coll-1', recipe_id: 'recipe-3', sort_order: 2 },
  { id: 'cr-3', collection_id: 'coll-1', recipe_id: 'recipe-5', sort_order: 3 },
  { id: 'cr-4', collection_id: 'coll-1', recipe_id: 'recipe-7', sort_order: 4 },
  // Nordic New Wave
  { id: 'cr-5', collection_id: 'coll-2', recipe_id: 'recipe-1', sort_order: 1 },
  { id: 'cr-6', collection_id: 'coll-2', recipe_id: 'recipe-2', sort_order: 2 },
  { id: 'cr-7', collection_id: 'coll-2', recipe_id: 'recipe-12', sort_order: 3 },
  // Dessert Revolution
  { id: 'cr-8', collection_id: 'coll-3', recipe_id: 'recipe-4', sort_order: 1 },
  { id: 'cr-9', collection_id: 'coll-3', recipe_id: 'recipe-6', sort_order: 2 },
];
